//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 21/12/2013 20:22:21
namespace ConsultaAereo.Web.ConsultaAereoProxy
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ConsultaAereo.Api.Models", "ConsultaAereo.Web.ConsultaAereoProxy");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("ConsultaAereo.Web.ConsultaAereoProxy", global::System.StringComparison.Ordinal))
            {
                return string.Concat("ConsultaAereo.Api.Models.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for PassagemAerea in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<PassagemAerea> PassagemAerea
        {
            get
            {
                if ((this._PassagemAerea == null))
                {
                    this._PassagemAerea = base.CreateQuery<PassagemAerea>("PassagemAerea");
                }
                return this._PassagemAerea;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<PassagemAerea> _PassagemAerea;
        /// <summary>
        /// There are no comments for Aeroporto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Aeroporto> Aeroporto
        {
            get
            {
                if ((this._Aeroporto == null))
                {
                    this._Aeroporto = base.CreateQuery<Aeroporto>("Aeroporto");
                }
                return this._Aeroporto;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Aeroporto> _Aeroporto;
        /// <summary>
        /// There are no comments for PassagemAerea in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToPassagemAerea(PassagemAerea passagemAerea)
        {
            base.AddObject("PassagemAerea", passagemAerea);
        }
        /// <summary>
        /// There are no comments for Aeroporto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToAeroporto(Aeroporto aeroporto)
        {
            base.AddObject("Aeroporto", aeroporto);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"ConsultaAereo.Api.Models\" xmlns=\"http://schemas.microsoft.com/ado/200" +
                "9/11/edm\"><EntityType Name=\"PassagemAerea\"><Key><PropertyRef Name=\"Id\" /></Key><" +
                "Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"DataIda\" " +
                "Type=\"Edm.DateTime\" Nullable=\"false\" /><Property Name=\"DataVolta\" Type=\"Edm.Date" +
                "Time\" /><Property Name=\"QuantidadePax\" Type=\"Edm.Int32\" Nullable=\"false\" /><Navi" +
                "gationProperty Name=\"Origem\" Relationship=\"ConsultaAereo.Api.Models.ConsultaAere" +
                "o_Api_Models_PassagemAerea_Origem_ConsultaAereo_Api_Models_Aeroporto_OrigemPartn" +
                "er\" ToRole=\"Origem\" FromRole=\"OrigemPartner\" /><NavigationProperty Name=\"Destino" +
                "\" Relationship=\"ConsultaAereo.Api.Models.ConsultaAereo_Api_Models_PassagemAerea_" +
                "Destino_ConsultaAereo_Api_Models_Aeroporto_DestinoPartner\" ToRole=\"Destino\" From" +
                "Role=\"DestinoPartner\" /></EntityType><EntityType Name=\"Aeroporto\"><Key><Property" +
                "Ref Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><P" +
                "roperty Name=\"Sigla\" Type=\"Edm.String\" /><Property Name=\"NomeCompleto\" Type=\"Edm" +
                ".String\" /></EntityType><Association Name=\"ConsultaAereo_Api_Models_PassagemAere" +
                "a_Origem_ConsultaAereo_Api_Models_Aeroporto_OrigemPartner\"><End Type=\"ConsultaAe" +
                "reo.Api.Models.Aeroporto\" Role=\"Origem\" Multiplicity=\"0..1\" /><End Type=\"Consult" +
                "aAereo.Api.Models.PassagemAerea\" Role=\"OrigemPartner\" Multiplicity=\"0..1\" /></As" +
                "sociation><Association Name=\"ConsultaAereo_Api_Models_PassagemAerea_Destino_Cons" +
                "ultaAereo_Api_Models_Aeroporto_DestinoPartner\"><End Type=\"ConsultaAereo.Api.Mode" +
                "ls.Aeroporto\" Role=\"Destino\" Multiplicity=\"0..1\" /><End Type=\"ConsultaAereo.Api." +
                "Models.PassagemAerea\" Role=\"DestinoPartner\" Multiplicity=\"0..1\" /></Association>" +
                "<EntityContainer Name=\"Container\" m:IsDefaultEntityContainer=\"true\"><EntitySet N" +
                "ame=\"PassagemAerea\" EntityType=\"ConsultaAereo.Api.Models.PassagemAerea\" /><Entit" +
                "ySet Name=\"Aeroporto\" EntityType=\"ConsultaAereo.Api.Models.Aeroporto\" /><Associa" +
                "tionSet Name=\"ConsultaAereo_Api_Models_PassagemAerea_Origem_ConsultaAereo_Api_Mo" +
                "dels_Aeroporto_OrigemPartnerSet\" Association=\"ConsultaAereo.Api.Models.ConsultaA" +
                "ereo_Api_Models_PassagemAerea_Origem_ConsultaAereo_Api_Models_Aeroporto_OrigemPa" +
                "rtner\"><End Role=\"OrigemPartner\" EntitySet=\"PassagemAerea\" /><End Role=\"Origem\" " +
                "EntitySet=\"Aeroporto\" /></AssociationSet><AssociationSet Name=\"ConsultaAereo_Api" +
                "_Models_PassagemAerea_Destino_ConsultaAereo_Api_Models_Aeroporto_DestinoPartnerS" +
                "et\" Association=\"ConsultaAereo.Api.Models.ConsultaAereo_Api_Models_PassagemAerea" +
                "_Destino_ConsultaAereo_Api_Models_Aeroporto_DestinoPartner\"><End Role=\"DestinoPa" +
                "rtner\" EntitySet=\"PassagemAerea\" /><End Role=\"Destino\" EntitySet=\"Aeroporto\" /><" +
                "/AssociationSet></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ConsultaAereo.Api.Models.PassagemAerea in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class PassagemAerea
    {
        /// <summary>
        /// Create a new PassagemAerea object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dataIda">Initial value of DataIda.</param>
        /// <param name="quantidadePax">Initial value of QuantidadePax.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static PassagemAerea CreatePassagemAerea(int ID, global::System.DateTime dataIda, int quantidadePax)
        {
            PassagemAerea passagemAerea = new PassagemAerea();
            passagemAerea.Id = ID;
            passagemAerea.DataIda = dataIda;
            passagemAerea.QuantidadePax = quantidadePax;
            return passagemAerea;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property DataIda in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DataIda
        {
            get
            {
                return this._DataIda;
            }
            set
            {
                this.OnDataIdaChanging(value);
                this._DataIda = value;
                this.OnDataIdaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DataIda;
        partial void OnDataIdaChanging(global::System.DateTime value);
        partial void OnDataIdaChanged();
        /// <summary>
        /// There are no comments for Property DataVolta in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DataVolta
        {
            get
            {
                return this._DataVolta;
            }
            set
            {
                this.OnDataVoltaChanging(value);
                this._DataVolta = value;
                this.OnDataVoltaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DataVolta;
        partial void OnDataVoltaChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDataVoltaChanged();
        /// <summary>
        /// There are no comments for Property QuantidadePax in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuantidadePax
        {
            get
            {
                return this._QuantidadePax;
            }
            set
            {
                this.OnQuantidadePaxChanging(value);
                this._QuantidadePax = value;
                this.OnQuantidadePaxChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuantidadePax;
        partial void OnQuantidadePaxChanging(int value);
        partial void OnQuantidadePaxChanged();
        /// <summary>
        /// There are no comments for Origem in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Aeroporto Origem
        {
            get
            {
                return this._Origem;
            }
            set
            {
                this._Origem = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Aeroporto _Origem;
        /// <summary>
        /// There are no comments for Destino in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Aeroporto Destino
        {
            get
            {
                return this._Destino;
            }
            set
            {
                this._Destino = value;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Aeroporto _Destino;
    }
    /// <summary>
    /// There are no comments for ConsultaAereo.Api.Models.Aeroporto in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Aeroporto
    {
        /// <summary>
        /// Create a new Aeroporto object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Aeroporto CreateAeroporto(int ID)
        {
            Aeroporto aeroporto = new Aeroporto();
            aeroporto.Id = ID;
            return aeroporto;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Sigla in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Sigla
        {
            get
            {
                return this._Sigla;
            }
            set
            {
                this.OnSiglaChanging(value);
                this._Sigla = value;
                this.OnSiglaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Sigla;
        partial void OnSiglaChanging(string value);
        partial void OnSiglaChanged();
        /// <summary>
        /// There are no comments for Property NomeCompleto in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string NomeCompleto
        {
            get
            {
                return this._NomeCompleto;
            }
            set
            {
                this.OnNomeCompletoChanging(value);
                this._NomeCompleto = value;
                this.OnNomeCompletoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _NomeCompleto;
        partial void OnNomeCompletoChanging(string value);
        partial void OnNomeCompletoChanged();
    }
}
